### ISSUE TITLE
Content Module disappears in Briefing Book

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#214] opened 2015-06-24 13:34 UTC
@CTLocalGovTeam We found a pretty serious issue, however, we don't have any repro steps. 

We do have a book that has the issue. 
http://54.203.249.87/BriefingBookAuthor/?bookId=77bb1c8a7ff84d2e975d6a93e2a58b9e
( Copy - Crash Analysis Risk Summary - Please use this COPY version not the original) 

Issue: The Content Module disappears from a newly authored book although the book was saved. 
The content module cannot be delete manually because the "delete button" does not exist. 
(I noticed that modules, I thought I saved disappeared before in testing but I assumed it was my user error and I accidentally hit the "delete button". However, now that we see this in the content module it makes me believe that it may not be limited to just that module. 

Note: Please assess using the most recent version of the application here: https://github.com/Esri/briefing-book/tree/master

**Comment by CTLocalGovTeam** [comment] 2015-06-25 16:11
@LindsayThomas 
We are able to repro this now.
**Steps to reproduce:**
1. Add a new page in an existing book
2. Choose any layout except the first one (layout should have two modules in any column)
3. Delete any module from the column containing two modules
4. Save and reopen the book
5. Observe that the column on that page does not display any module, whereas it should have displayed one that was not deleted.

The same steps can be used for the Contents page too. If you delete a module from the column that contains two modules, both modules get deleted.

**Root cause and fix:**
The logic to delete a module had an error in that it was deleting two modules instead of only one.
It was actually trying to delete the same module twice, as a result, the second module was getting deleted.
This can be fixed by enforcing a check if the module is present before deleting it. This requires a code change in `widgets/mapbook-collection/module-renderer.js`. The impact of this code change is localized to only when deleting a module.

Please see screenshot below to help you visualize the code change.

![image](https://cloud.githubusercontent.com/assets/2959186/8359282/e9bf6c1a-1b82-11e5-9c89-10911015a363.png)

**Comment by LindsayThomas** [comment] 2015-06-25 21:24
@CTLocalGovTeam Could we please get this fix into the codebase? 
(Please branch \ sync off of master before making the change)

**Comment by LindsayThomas** [comment] 2015-06-26 13:01
@CTLocalGovTeam Thanks for the quick turnaround. I will look at this as soon as I can.

**Comment by LindsayThomas** [comment] 2015-06-26 17:22
Note: if you remove the bottom module then the issue doesn't exist. But if you remove the middle module then the issue exist.

The fix above resolves the issue.

**Closed** 2015-06-26 21:13 UTC
